name = input("What is your name? ")
print("Hello", name)
age = input("What is your age? ")
print("You are",age,"years old")
university = input("What is your university? ")
print("You are studying at", university)
degree = input("What is your degree? ")
print("You are pursuing a degree in", degree)
target_salary = input("What is your target salary? ")
print("Your target salary is $", target_salary)