name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://jsonplaceholder.typicode.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install API dependencies
        run: |
          cd api-testing
          pip install -r requirements.txt

      - name: Run API tests
        run: |
          cd api-testing
          python -m pytest tests -v --junitxml=test-results.xml

      - name: Install Playwright dependencies
        run: |
          cd playwright
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run Playwright tests
        env:
          PLAYWRIGHT_BASE_URL: https://www.saucedemo.com/
          TEST_USERNAME: standard_user
          TEST_PASSWORD: secret_sauce
        run: |
          cd playwright
          python -m pytest tests -v --html=test-results/report.html --self-contained-html

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright/test-results/report.html

      - name: Upload Playwright test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: playwright-test-log
         path: playwright/test-results/test.log